In [1]:
import pandas as pd

In [7]:
data = pd.read_csv('telecom_churn_data.csv')
data.shape

(99999, 226)

In [8]:
data.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,197.385,...,0,1.0,1.0,1.0,NaN,968,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,34.047,...,0,NaN,1.0,1.0,NaN,1006,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,167.690,...,0,NaN,NaN,NaN,1.0,1103,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,221.338,...,0,NaN,NaN,NaN,NaN,2491,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.636,...,0,0.0,NaN,NaN,NaN,1526,0.0,0.0,0.00,0.00

In [25]:
des = data.describe()

In [32]:
des.iloc[:, 9:20]

,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8
count,96062.000000,96140.000000,94621.000000,92254.000000,96062.000000,96140.000000,94621.000000,92254.000000,96062.000000,96140.000000,94621.000000
mean,132.395875,133.670805,133.018098,130.302327,197.935577,197.045133,196.574803,190.337222,9.950013,7.149898,7.292981
std,297.207406,308.794148,308.951589,308.477668,316.851613,325.862803,327.170662,319.396092,72.825411,73.447948,68.402466
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.380000,6.660000,6.460000,5.330000,34.730000,32.190000,31.630000,27.130000,0.000000,0.000000,0.000000
50%,34.310000,32.330000,32.360000,29.840000,96.310000,91.735000,92.140000,87.290000,0.000000,0.000000,0.000000
75%,118.740000,115.595000,115.860000,112.130000,231.860000,226.815000,228.260000,220.505000,0.000000,0.000000,0.000000
max,7376.710000,8157.780000,10752.560000,10427.460000,8362.360000,9667.130000,14007.340000,10310.760000,13724.380000,15371.040000,13095.360000

In [6]:
pd.read_excel('Data+Dictionary-+Telecom+Churn+Case+Study.xlsx%3FX-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com@kaggle-161607.iam.gserviceaccount.com%2F20201111%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20201111T023819Z&X-Goog-Expir.xlsx')

     Acronyms                                           Descriptions
0   MOBILE_NUMBER                              Customer phone number
1       CIRCLE_ID  Telecom circle area to which the customer belo...
2             LOC           Local calls - within same telecom circle
3             STD             STD calls - outside the calling circle
4              IC                                     Incoming calls
5              OG                                     Outgoing calls
6             T2T  Operator T to T, i.e. within same operator (mo...
7         T2M                    Operator T to other operator mobile
8         T2O                Operator T to other operator fixed line
9         T2F                         Operator T to fixed lines of T
10        T2C                     Operator T to itâ€™s own call center
11       ARPU                               Average revenue per user
12        MOU                         Minutes of usage - voice calls
13        AON      Age on network - number of days the customer i...
14       ONNET     All kind of calls within the same operator net...
15     OFFNET       All kind of calls outside the operator T network
16           ROAM  Indicates that customer is in roaming zone dur...
17         SPL                                         Special calls
18        ISD                                              ISD calls
19       RECH                                               Recharge
20        NUM                                                 Number
21        AMT                               Amount in local currency
22        MAX                                                Maximum
23       DATA                                        Mobile internet
24         3G                                             3G network
25         AV                                                Average
26        VOL                   Mobile internet usage volume (in MB)
27         2G                                             2G network
28        PCK                 Prepaid service schemes called - PACKS
29      NIGHT         Scheme to use during specific night hours only
30    MONTHLY      Service schemes with validity equivalent to a ...
31      SACHET     Service schemes with validity smaller than a m...
32        *.6                              KPI for the month of June
33        *.7                              KPI for the month of July
34        *.8                            KPI for the month of August
35        *.9                         KPI for the month of September
36        FB_USER  Service scheme to avail services of Facebook a...
37        VBC      Volume based cost - when no specific scheme is...

In [16]:
def print_full(x):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 2000)
    pd.set_option('display.float_format', '{:20,.2f}'.format)
    pd.set_option('display.max_colwidth', None)
    print(x)
    pd.reset_option('display.max_rows')
    pd.reset_option('display.max_columns')
    pd.reset_option('display.width')
    pd.reset_option('display.float_format')
    pd.reset_option('display.max_colwidth')

In [20]:
print_full(data.iloc[0])

mobile_number                        7000842753
circle_id                                   109
loc_og_t2o_mou                             0.00
std_og_t2o_mou                             0.00
loc_ic_t2o_mou                             0.00
last_date_of_month_6                  6/30/2014
last_date_of_month_7                  7/31/2014
last_date_of_month_8                  8/31/2014
last_date_of_month_9                  9/30/2014
arpu_6                                   197.38
arpu_7                                   214.82
arpu_8                                   213.80
arpu_9                                    21.10
onnet_mou_6                                 NaN
onnet_mou_7                                 NaN
onnet_mou_8                                0.00
onnet_mou_9                                 NaN
offnet_mou_6                                NaN
offnet_mou_7                                NaN
offnet_mou_8                               0.00
offnet_mou_9                                NaN
roam_ic_mou_6                               NaN
roam_ic_mou_7                               NaN
roam_ic_mou_8                              0.00
roam_ic_mou_9                               NaN
roam_og_mou_6                               NaN
roam_og_mou_7                               NaN
roam_og_mou_8                              0.00
roam_og_mou_9                               NaN
loc_og_t2t_mou_6                            NaN
loc_og_t2t_mou_7                            NaN
loc_og_t2t_mou_8                           0.00
loc_og_t2t_mou_9                            NaN
loc_og_t2m_mou_6                            NaN
loc_og_t2m_mou_7                            NaN
loc_og_t2m_mou_8                           0.00
loc_og_t2m_mou_9                            NaN
loc_og_t2f_mou_6                            NaN
loc_og_t2f_mou_7                            NaN
loc_og_t2f_mou_8                           0.00
loc_og_t2f_mou_9                            NaN
loc_og_t2c_mou_6                            NaN
loc_og_t2c_mou_7                            NaN
loc_og_t2c_mou_8                           0.00
loc_og_t2c_mou_9                            NaN
loc_og_mou_6                                NaN
loc_og_mou_7                                NaN
loc_og_mou_8                               0.00
loc_og_mou_9                                NaN
std_og_t2t_mou_6                            NaN
std_og_t2t_mou_7                            NaN
std_og_t2t_mou_8                           0.00
std_og_t2t_mou_9                            NaN
std_og_t2m_mou_6                            NaN
std_og_t2m_mou_7                            NaN
std_og_t2m_mou_8                           0.00
std_og_t2m_mou_9                            NaN
std_og_t2f_mou_6                            NaN
std_og_t2f_mou_7                            NaN
std_og_t2f_mou_8                           0.00
std_og_t2f_mou_9                            NaN
std_og_t2c_mou_6                            NaN
std_og_t2c_mou_7                            NaN
std_og_t2c_mou_8                           0.00
std_og_t2c_mou_9                            NaN
std_og_mou_6                                NaN
std_og_mou_7                                NaN
std_og_mou_8                               0.00
std_og_mou_9                                NaN
isd_og_mou_6                                NaN
isd_og_mou_7                                NaN
isd_og_mou_8                               0.00
isd_og_mou_9                                NaN
spl_og_mou_6                                NaN
spl_og_mou_7                                NaN
spl_og_mou_8                               0.00
spl_og_mou_9                                NaN
og_others_6                                 NaN
og_others_7                                 NaN
og_others_8                                0.00
og_others_9                                 NaN
total_og_mou_6                             0.00
total_og_mou_7                             0.00
total_og_mou_8                             0.00
total_og_mou_9                             0.00
loc_ic_t2t_mou_6                            NaN
loc_ic_t2t_mou_7                            NaN
loc_ic_t2t_mou_8                           0.16
loc_ic_t2t_mou_9                            NaN
loc_ic_t2m_mou_6                            NaN
loc_ic_t2m_mou_7                            NaN
loc_ic_t2m_mou_8                           4.13
loc_ic_t2m_mou_9                            NaN
loc_ic_t2f_mou_6                            NaN
loc_ic_t2f_mou_7                            NaN
loc_ic_t2f_mou_8                           1.15
loc_ic_t2f_mou_9                            NaN
loc_ic_mou_6                                NaN
loc_ic_mou_7                                NaN
loc_ic_mou_8                               5.44
loc_ic_mou_9                                NaN
std_ic_t2t_mou_6                            NaN
std_ic_t2t_mou_7                            NaN
std_ic_t2t_mou_8                           0.00
std_ic_t2t_mou_9                            NaN
std_ic_t2m_mou_6                            NaN
std_ic_t2m_mou_7                            NaN
std_ic_t2m_mou_8                           0.00
std_ic_t2m_mou_9                            NaN
std_ic_t2f_mou_6                            NaN
std_ic_t2f_mou_7                            NaN
std_ic_t2f_mou_8                           0.00
std_ic_t2f_mou_9                            NaN
std_ic_t2o_mou_6                            NaN
std_ic_t2o_mou_7                            NaN
std_ic_t2o_mou_8                           0.00
std_ic_t2o_mou_9                            NaN
std_ic_mou_6                                NaN
std_ic_mou_7                                NaN
std_ic_mou_8                               0.00
std_ic_mou_9                                NaN
total_ic_mou_6                             0.00
total_ic_mou_7                             0.00
total_ic_mou_8                             5.44
total_ic_mou_9                             0.00
spl_ic_mou_6                                NaN
spl_ic_mou_7                                NaN
spl_ic_mou_8                               0.00
spl_ic_mou_9                                NaN
isd_ic_mou_6                                NaN
isd_ic_mou_7                                NaN
isd_ic_mou_8                               0.00
isd_ic_mou_9                                NaN
ic_others_6                                 NaN
ic_others_7                                 NaN
ic_others_8                                0.00
ic_others_9                                 NaN
total_rech_num_6                              4
total_rech_num_7                              3
total_rech_num_8                              2
total_rech_num_9                              6
total_rech_amt_6                            362
total_rech_amt_7                            252
total_rech_amt_8                            252
total_rech_amt_9                              0
max_rech_amt_6                              252
max_rech_amt_7                              252
max_rech_amt_8                              252
max_rech_amt_9                                0
date_of_last_rech_6                   6/21/2014
date_of_last_rech_7                   7/16/2014
date_of_last_rech_8                    8/8/2014
date_of_last_rech_9                   9/28/2014
last_day_rch_amt_6                          252
last_day_rch_amt_7                          252
last_day_rch_amt_8                          252
last_day_rch_amt_9                            0
date_of_last_rech_data_6              6/21/2014
date_of_last_rech_data_7              7/16/2014
date_of_last_rech_data_8               8/8/2014
date_of_last_rech_data_9                    NaN
total_rech_data_6                          1.00
total_rech_data_7                          1.00
total_rech_data_8                          1.00
total_rech_data_9                           NaN
max_rech_data_6                          252.00
max_rech_data_7                          252.00
max_rech_data_8                          252.00
max_rech_data_9                             NaN
count_rech_2g_6                            0.00
count_rech_2g_7                            0.00
count_rech_2g_8                            0.00
count_rech_2g_9                             NaN
count_rech_3g_6                            1.00
count_rech_3g_7                            1.00
count_rech_3g_8                            1.00
count_rech_3g_9                             NaN
av_rech_amt_data_6                       252.00
av_rech_amt_data_7                       252.00
av_rech_amt_data_8                       252.00
av_rech_amt_data_9                          NaN
vol_2g_mb_6                               30.13
vol_2g_mb_7                                1.32
vol_2g_mb_8                                5.75
vol_2g_mb_9                                0.00
vol_3g_mb_6                               83.57
vol_3g_mb_7                              150.76
vol_3g_mb_8                              109.61
vol_3g_mb_9                                0.00
arpu_3g_6                                212.17
arpu_3g_7                                212.17
arpu_3g_8                                212.17
arpu_3g_9                                   NaN
arpu_2g_6                                212.17
arpu_2g_7                                212.17
arpu_2g_8                                212.17
arpu_2g_9                                   NaN
night_pck_user_6                           0.00
night_pck_user_7                           0.00
night_pck_user_8                           0.00
night_pck_user_9                            NaN
monthly_2g_6                                  0
monthly_2g_7                                  0
monthly_2g_8                                  0
monthly_2g_9                                  0
sachet_2g_6                                   0
sachet_2g_7                                   0
sachet_2g_8                                   0
sachet_2g_9                                   0
monthly_3g_6                                  1
monthly_3g_7                                  1
monthly_3g_8                                  1
monthly_3g_9                                  0
sachet_3g_6                                   0
sachet_3g_7                                   0
sachet_3g_8                                   0
sachet_3g_9                                   0
fb_user_6                                  1.00
fb_user_7                                  1.00
fb_user_8                                  1.00
fb_user_9                                   NaN
aon                                         968
aug_vbc_3g                                30.40
jul_vbc_3g                                 0.00
jun_vbc_3g                               101.20
sep_vbc_3g                                 3.58
Name: 0, dtype: object

In [11]:
list(data.columns)

['mobile_number',
 'circle_id',
 'loc_og_t2o_mou',
 'std_og_t2o_mou',
 'loc_ic_t2o_mou',
 'last_date_of_month_6',
 'last_date_of_month_7',
 'last_date_of_month_8',
 'last_date_of_month_9',
 'arpu_6',
 'arpu_7',
 'arpu_8',
 'arpu_9',
 'onnet_mou_6',
 'onnet_mou_7',
 'onnet_mou_8',
 'onnet_mou_9',
 'offnet_mou_6',
 'offnet_mou_7',
 'offnet_mou_8',
 'offnet_mou_9',
 'roam_ic_mou_6',
 'roam_ic_mou_7',
 'roam_ic_mou_8',
 'roam_ic_mou_9',
 'roam_og_mou_6',
 'roam_og_mou_7',
 'roam_og_mou_8',
 'roam_og_mou_9',
 'loc_og_t2t_mou_6',
 'loc_og_t2t_mou_7',
 'loc_og_t2t_mou_8',
 'loc_og_t2t_mou_9',
 'loc_og_t2m_mou_6',
 'loc_og_t2m_mou_7',
 'loc_og_t2m_mou_8',
 'loc_og_t2m_mou_9',
 'loc_og_t2f_mou_6',
 'loc_og_t2f_mou_7',
 'loc_og_t2f_mou_8',
 'loc_og_t2f_mou_9',
 'loc_og_t2c_mou_6',
 'loc_og_t2c_mou_7',
 'loc_og_t2c_mou_8',
 'loc_og_t2c_mou_9',
 'loc_og_mou_6',
 'loc_og_mou_7',
 'loc_og_mou_8',
 'loc_og_mou_9',
 'std_og_t2t_mou_6',
 'std_og_t2t_mou_7',
 'std_og_t2t_mou_8',
 'std_og_t2t_mou_9',
 'std_og_t2m_mou_6',
 'std_og_t2m_mou_7',
 'std_og_t2m_mou_8',
 'std_og_t2m_mou_9',
 'std_og_t2f_mou_6',
 'std_og_t2f_mou_7',
 'std_og_t2f_mou_8',
 'std_og_t2f_mou_9',
 'std_og_t2c_mou_6',
 'std_og_t2c_mou_7',
 'std_og_t2c_mou_8',
 'std_og_t2c_mou_9',
 'std_og_mou_6',
 'std_og_mou_7',
 'std_og_mou_8',
 'std_og_mou_9',
 'isd_og_mou_6',
 'isd_og_mou_7',
 'isd_og_mou_8',
 'isd_og_mou_9',
 'spl_og_mou_6',
 'spl_og_mou_7',
 'spl_og_mou_8',
 'spl_og_mou_9',
 'og_others_6',
 'og_others_7',
 'og_others_8',
 'og_others_9',
 'total_og_mou_6',
 'total_og_mou_7',
 'total_og_mou_8',
 'total_og_mou_9',
 'loc_ic_t2t_mou_6',
 'loc_ic_t2t_mou_7',
 'loc_ic_t2t_mou_8',
 'loc_ic_t2t_mou_9',
 'loc_ic_t2m_mou_6',
 'loc_ic_t2m_mou_7',
 'loc_ic_t2m_mou_8',
 'loc_ic_t2m_mou_9',
 'loc_ic_t2f_mou_6',
 'loc_ic_t2f_mou_7',
 'loc_ic_t2f_mou_8',
 'loc_ic_t2f_mou_9',
 'loc_ic_mou_6',
 'loc_ic_mou_7',
 'loc_ic_mou_8',
 'loc_ic_mou_9',
 'std_ic_t2t_mou_6',
 'std_ic_t2t_mou_7',
 'std_ic_t2t_mou_8',
 'std_ic_t2t_mou_9',
 'std_ic_t2m_mou_6',
 'std_ic_t2m_mou_7',
 'std_ic_t2m_mou_8',
 'std_ic_t2m_mou_9',
 'std_ic_t2f_mou_6',
 'std_ic_t2f_mou_7',
 'std_ic_t2f_mou_8',
 'std_ic_t2f_mou_9',
 'std_ic_t2o_mou_6',
 'std_ic_t2o_mou_7',
 'std_ic_t2o_mou_8',
 'std_ic_t2o_mou_9',
 'std_ic_mou_6',
 'std_ic_mou_7',
 'std_ic_mou_8',
 'std_ic_mou_9',
 'total_ic_mou_6',
 'total_ic_mou_7',
 'total_ic_mou_8',
 'total_ic_mou_9',
 'spl_ic_mou_6',
 'spl_ic_mou_7',
 'spl_ic_mou_8',
 'spl_ic_mou_9',
 'isd_ic_mou_6',
 'isd_ic_mou_7',
 'isd_ic_mou_8',
 'isd_ic_mou_9',
 'ic_others_6',
 'ic_others_7',
 'ic_others_8',
 'ic_others_9',
 'total_rech_num_6',
 'total_rech_num_7',
 'total_rech_num_8',
 'total_rech_num_9',
 'total_rech_amt_6',
 'total_rech_amt_7',
 'total_rech_amt_8',
 'total_rech_amt_9',
 'max_rech_amt_6',
 'max_rech_amt_7',
 'max_rech_amt_8',
 'max_rech_amt_9',
 'date_of_last_rech_6',
 'date_of_last_rech_7',
 'date_of_last_rech_8',
 'date_of_last_rech_9',
 'last_day_rch_amt_6',
 'last_day_rch_amt_7',
 'last_day_rch_amt_8',
 'last_day_rch_amt_9',
 'date_of_last_rech_data_6',
 'date_of_last_rech_data_7',
 'date_of_last_rech_data_8',
 'date_of_last_rech_data_9',
 'total_rech_data_6',
 'total_rech_data_7',
 'total_rech_data_8',
 'total_rech_data_9',
 'max_rech_data_6',
 'max_rech_data_7',
 'max_rech_data_8',
 'max_rech_data_9',
 'count_rech_2g_6',
 'count_rech_2g_7',
 'count_rech_2g_8',
 'count_rech_2g_9',
 'count_rech_3g_6',
 'count_rech_3g_7',
 'count_rech_3g_8',
 'count_rech_3g_9',
 'av_rech_amt_data_6',
 'av_rech_amt_data_7',
 'av_rech_amt_data_8',
 'av_rech_amt_data_9',
 'vol_2g_mb_6',
 'vol_2g_mb_7',
 'vol_2g_mb_8',
 'vol_2g_mb_9',
 'vol_3g_mb_6',
 'vol_3g_mb_7',
 'vol_3g_mb_8',
 'vol_3g_mb_9',
 'arpu_3g_6',
 'arpu_3g_7',
 'arpu_3g_8',
 'arpu_3g_9',
 'arpu_2g_6',
 'arpu_2g_7',
 'arpu_2g_8',
 'arpu_2g_9',
 'night_pck_user_6',
 'night_pck_user_7',
 'night_pck_user_8',
 'night_pck_user_9',
 'monthly_2g_6',
 'monthly_2g_7',
 'monthly_2g_8',
 'monthly_2g_9',
 'sachet_2g_6',
 'sachet_2g_7',
 'sachet_2g_8',
 'sachet_2g_9',
 'monthly_3g_6',
 'monthly_3g_7',
 'monthly_3g_8',
 'monthly_3g_9',
 'sachet_3g_6',
 'sachet_3g_7',
 'sachet_3g_8',
 'sachet_3g_9',
 'fb_user_6',
 'fb_user_7',
 'fb_user_8',
 'fb_user_9',
 'aon',
 'aug_vbc_3g',
 'jul_vbc_3g',
 'jun_vbc_3g',
 'sep_vbc_3g']